# Generated by Django 4.1.7 on 2023-03-20 06:40

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course_duration_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson_title',
            field=models.CharField(default='Lesson', max_length=255),
        ),
        migrations.AddField(
            model_name='course',
            name='lesson_video',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='lesson_1_video'),
        ),
    ]
