# Generated by Django 4.1.7 on 2023-03-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='uncategorized', max_length=255),
        ),
    ]
